function C = getControls(this)
%getControls Get the controls description string

C = [ ...
    '----- CONTROLS ---------------------------' newline ...
    newline ...
    'NAVIGATION' newline ...
    '  ±1 frame [' char(8592) ',' char(8594) ']' newline ...
    '  Rewind [Page down]' newline ...
    '  Save [s]' newline ...
    newline ...
    'SHAPES' newline ...
    '  Split [c]' newline ...
    '  Merge [m]' newline ...
    '  Delete [Del]' newline ...
    '  First free shape [Page up]' newline ...
    newline ...
    'CELLS' newline ...
    '  New cell [n]' newline ...
    '  Include shape [left click]' newline ...
    '  Skip [middle click]', newline ...
    '  End [right click]' newline ...
    '  Cell to shape [k]' newline ...
    '  Export [S]'];
