function C = getControls(this)
%getControls Get the controls description string

C = [ ...
    '----- CONTROLS ---------------------------' newline ...
    newline ...
    'VIEW' newline];

if this.Visu.viewLocal
    C = [C '  Global [g]' newline '  Local [l]    #' newline];
else
    C = [C '  Global [g]   #' newline '  Local [l]' newline];
end

C = [C '  Size [w...]                  ' num2str(this.Visu.lsz) ' pix' newline ...
    '  Toggle fragments view [F]' newline ...
    '  Toggle trajectories view [T]' newline ...
    '  Toggle quarantine view [Q]' newline ...
    newline ...
    'NAVIGATION' newline ...
    '  Play/pause [space]' newline ...
    '  Frames per second [v...]     ' num2str(this.Visu.fps, '%02i') ' fps' newline ...
    '  Flashback and play [b]' newline ...
    '  Flashback duration [d...]    '  num2str(this.Visu.fbd) ' frames' newline ...
    '  ±1 frame [' char(8592) ',' char(8594) '] (on pause)' newline ...
    '  Rewind [Page down]' newline ...
    newline ...
    'FRAGMENTS' newline ...
    '  Select [Middle click]' newline ...
    '  Cut [c] (at t-1)' newline ...
    '  Toggle quarantine status [q]' newline ...
    '  Define as soma [Right click]' newline ...
    '  Define as centrosome [Right click]' newline ...
    '  Define as cone [Right click]' newline ...
    '  Save [s]' newline ...
    newline ...
    'TRAJECTORIES' newline ...
    '  Select trajectory [Left click]' newline ...
    '  Search trajectory [r...]' newline ...
    '  New trajectory [t]' newline ...
    '  Include fragment [+]' newline ...
    '  Remove fragment [-]', newline ...
    '  End [' char(8593) ']' newline ...
    '  Beginning [' char(8595) ']' newline ...
    '  Next doublon [n]' newline ...
    '  Flashback last fragment and play [f]' newline ...
    '  Export [S]'];
